---
title: "R Notebook: C. sordidus survey analysis - 2020/02/05"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


#Step 0: Load packages
```{r}
library(tidyverse)
library(brms)
library(tidybayes)
library(modelr) #for data_grid function
library(bayesplot)
library(gridExtra) #for plots
library(RColorBrewer) #for plots
library(cowplot) #for plots
library(scales) #for plots
```


#Step 1: Load data
```{r}
load("cso_surveys_data.Rdata")

##want to start with sordidus only, 2018/2019
str(cso_only_sum) #summed by transect, need to delete 2015

cso_only_sum_2018<-
  cso_only_sum  %>%
  filter(Year == "2018")  %>%
  droplevels()
str(cso_only_sum_2018)
##remove Nelson as Island level because not surveyed in 2018/2019

###data transformations
cso_only_sum_2018$lbio<-log(cso_only_sum_2018$sum_bio+1)
cso_only_sum_2018$ldens<-log(cso_only_sum_2018$sum_dens+1)


######sum by reef
cso_only_reef_2018<-
  cso_only_sum_2018  %>%
  group_by(Atoll, Island, Treatment)  %>%
  summarize(sum_bio_reef=sum(sum_bio),
            sum_dens_reef = sum(sum_dens))
str(cso_only_reef_2018)
cso_only_reef_2018
##None present at: GCB Eagle (rats), GCB South Brother (no rats), PB Grande Ile Coquillage (No rats)


##relevel treatment:
cso_only_sum_2018$treatment_b<-relevel(cso_only_sum_2018$Treatment, "Rats")


###for size distributions, need non-aggregated data:
###re-level for birdy effect: 
cso_only_2018$treatment_b<-relevel(cso_only_2018$Treatment, "Rats")
###try with log length
cso_only_2018$llength<-log(cso_only_2018$Length)

```


##Biomass models
```{r}
##Previous checks of distributions showed that hurdle gamma fits data the best
##Makes sense, since there are quite a few zeros in the data
#useful gamma info: https://rpubs.com/jwesner/gamma_glm
biomass_mod <- 
  brm(data = cso_only_sum_2018, family = hurdle_gamma(link="log"), #hurdle because quite a few zeros, gamma fits continuous non-negative data
      sum_bio  ~ treatment_b  + (1|Atoll),
      prior = c(prior(normal(0,1), class = "b"), ##weakly informative - allows any sort of bird/rat effect (sd = 1 because log link)
                prior(normal(0,1), class = "Intercept")), ##weakly informative
      iter = 5000, warmup = 1000, chains = 4, cores = 4, 
      control = list(adapt_delta = 0.999, max_treedepth = 15), 
      sample_prior="yes",
      file = "biomass_mod")
print(biomass_mod) ##no divergent transitions
plot(biomass_mod)
pp_check(biomass_mod) 
pairs(biomass_mod)
##pp_check shows some outlier samples from model, but overall diagnostics look okay (and better than other distributions)
prior_summary(biomass_mod)

#check plots of  posterior versus prior distributions: 

#intercept:
posterior_samples(biomass_mod) %>% 
  select(b_Intercept, prior_b) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()

#slope:
posterior_samples(biomass_mod) %>% 
  select(b_treatment_bNo_rats, prior_b) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()

#Compile posterior distributions:
biomass_post <- posterior_samples(biomass_mod)
median_hdi(biomass_post$b_treatment_bNo_rats, .width = .95) #median estimate = -0.28, ymin = -1.31, ymax = 0.84


#test hypothesis that birdy effect is > 0
hypothesis(biomass_mod, "treatment_bNo_rats>0") 
#evidence ratio = 0.45, posterior probability = 0.31

```



###Density
```{r}
density_mod <- 
  brm(data = cso_only_sum_2018, family = hurdle_gamma(link="log"),
      sum_dens  ~ treatment_b  + (1|Atoll),
      prior = c(prior(normal(0,1), class = "b"),
                prior(normal(0,1), class = "Intercept")),
      iter = 5000, warmup = 1000, chains = 4, cores = 4, 
      control = list(adapt_delta = 0.999, max_treedepth = 15), 
      sample_prior="yes",
      file = "density_mod")
print(density_mod)
plot(density_mod) 
pp_check(density_mod)
pairs(density_mod)
##all looks okay
prior_summary(density_mod)
#check plots of  posterior versus prior distributions: 

#intercept:
posterior_samples(density_mod) %>% 
  select(b_Intercept, prior_b) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()

#slope:
posterior_samples(density_mod) %>% 
  select(b_treatment_bNo_rats, prior_b) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()

#Compile posterior distributions:
density_post <- posterior_samples(density_mod)
median_hdi(density_post$b_treatment_bNo_rats, .width = .95) #median estimate = -0.35, ymin = -1.09, ymax = 0.49


#test hypothesis that birdy effect is > 0
hypothesis(density_mod, "treatment_bNo_rats>0") 
#evidence ratio = 0.24, posterior probability = 0.19
```


##Plot: boxplots of raw data
```{r}
bio_boxplot_no0<-
  cso_only_sum_2018 %>% 
  filter(sum_bio>0)%>% ##exclude zeros because hurdl emodel
  mutate(Treatment = factor(Treatment, levels=c("Rats", "No_rats")))  %>% #re-arrange to match posterior plots
  ggplot(aes(x=Treatment, y=sum_bio, fill=Treatment, alpha = 0.6, shape = Treatment)) + 
  geom_boxplot(outlier.size=0, outlier.stroke=0) +
  geom_point(stat="identity", size = 2, position = position_jitterdodge(dodge.width=.1)) + 
  scale_fill_manual(values = c("#DC3220", "#005AB5"))+
  scale_shape_manual(values = c(23,21)) + 
  scale_x_discrete(labels=c("rat-infested", "rat-free")) +
  scale_y_continuous(trans='log10')+ #plot on log scale because log link in model #, limits=c(0, 1000)
  theme_bw() + 
  xlab(" ")+
  ylab("Biomass (kg/ha)") +
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.text.x = element_text(size=16))
bio_boxplot_no0
  



dens_boxplot_no0<-
  cso_only_sum_2018 %>% 
  filter(sum_dens>0)%>% ##exclude zeros because hurdle model
  mutate(Treatment = factor(Treatment, levels=c("Rats", "No_rats")))  %>% #re-arrange to match posterior plots
  ggplot(aes(x=Treatment, y=sum_dens, fill=Treatment, alpha = 0.6, shape = Treatment)) + 
  geom_boxplot(outlier.size=0, outlier.stroke=0) +
  geom_point(stat="identity", size = 2, position = position_jitterdodge(dodge.width=.1)) + 
  scale_fill_manual(values = c("#DC3220", "#005AB5"))+
  scale_shape_manual(values = c(23,21)) + 
  scale_x_discrete(labels=c("rat-infested", "rat-free")) +
  scale_y_continuous(trans='log10')+ #plot on log scale because log link in model
  theme_bw() + 
  xlab(" ")+
  ylab("Density (ind/ha)") +
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.text.x = element_text(size=16))
dens_boxplot_no0

nrow(cso_only_sum_2018[cso_only_sum_2018$Treatment=="Rats"&cso_only_sum_2018$sum_dens>0,]) ##14
nrow(cso_only_sum_2018[cso_only_sum_2018$Treatment=="Rats",]) ##24
nrow(cso_only_sum_2018[cso_only_sum_2018$Treatment=="Rats"&cso_only_sum_2018$sum_dens==0,]) ##10

nrow(cso_only_sum_2018[cso_only_sum_2018$Treatment=="No_rats"&cso_only_sum_2018$sum_dens>0,]) ##8
nrow(cso_only_sum_2018[cso_only_sum_2018$Treatment=="No_rats",]) ##20
nrow(cso_only_sum_2018[cso_only_sum_2018$Treatment=="No_rats"&cso_only_sum_2018$sum_dens==0,]) ##12


```

#Posterior plots
```{r}
##Biomass
bio_post_plot<-
biomass_mod %>%
  spread_draws(b_treatment_bNo_rats) %>%
 # mutate(exp_b=exp(b_treatment_bNo_rats))%>%
  ggplot(aes(y = 0, x = b_treatment_bNo_rats, fill = stat(x < 0))) +
  stat_halfeyeh(point_interval=median_hdi, .width=.95, fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#005AB5", "#DC3220"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("Biomass")+
  ylab("") +
  scale_y_continuous(NULL, breaks = NULL) +
  scale_x_continuous(limits=c(-2.5, 2.5), breaks=seq(-2, 2,1))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.title.y = element_text(size=16, face="bold"))
bio_post_plot



dens_post_plot<-
density_mod %>%
  spread_draws(b_treatment_bNo_rats) %>%
 # mutate(exp_b=exp(b_treatment_bNo_rats))%>%
  ggplot(aes(y = 0, x = b_treatment_bNo_rats, fill = stat(x < 0))) +
  stat_halfeyeh(point_interval=median_hdi, .width=.95, fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#005AB5", "#DC3220"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("Density")+
  ylab("") +
  scale_y_continuous(NULL, breaks = NULL) +
  scale_x_continuous(limits=c(-2.5, 2.5), breaks=seq(-2, 2,1))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.title.y = element_text(size=16, face="bold"))
dens_post_plot

```



##Models: size distributions
```{r}
##did model comparisons to check distributions
##gaussian, lognormal, etc. had really bad fits.
##skewnormal and exgaussian both seemed okay - exgaussian is similar to skew normal, but has fatter tails (which matches this distribution)
##plus pp_check and model comparisons with loo indicated WAY better fit with exgaussian. 
##decription of exgaussian in brms pdf: https://arxiv.org/pdf/1905.09501.pdf - advantages include can directly measure right-skewness (beta parameter) in addition to mean (mu). - both of these parameters are of interest for size distribution data
 
size_mod_ex_gaus_wprior<- 
 brm(bf(Length ~ treatment_b + (1|Atoll),
        beta~treatment_b),
      data = cso_only_2018, family = exgaussian(),
       iter = 3000, warmup = 1000, chains = 4, cores = 4,
        prior = c(prior(normal(15,1), class = "Intercept"), #weakly informative prior based on mean length
                prior(normal(0,10), class = "b"), #weakly informative - allow any bird-rat effect
                prior(lognormal(0,1), dpar = "beta", class = "Intercept"), #beta must be > 0 in exgaussian dist.
                 prior(normal(0,1), dpar = "beta", class = "b"), #weakly informative - allow any bird-rat effect
                prior(lognormal(0,1), class = "sigma")),  ###sigma must be > 0, having issues with sampling when using default prior, so                                                                  constrain to positive (doesn't change parameter estimates, just helped sampling)
      control = list(adapt_delta = 0.9999, max_treedepth = 20),
           sample_prior="yes",
      file = "size_mod_ex_gaus_wprior")
print(size_mod_ex_gaus_wprior) ###only 1 divergent transitions, much faster sampling time, ESS looks good
pp_check(size_mod_ex_gaus_wprior) ##looks so much better than any other distribution!
plot(size_mod_ex_gaus_wprior, ask = FALSE)
prior_summary(size_mod_ex_gaus_wprior)


#check plots of priors:
size_mod_ex_gaus_wprior %>% 
  prior_summary() %>% #don't need this line when plotting priors before running the model
  mutate(label = pmap_chr(select(., -prior), paste)) %>% 
  parse_dist(prior) %>% 
  ggplot(aes(y = 0, dist = .dist, args = .args)) + 
  stat_dist_halfeyeh() + 
  geom_text(aes(label = prior), x = 0, y = .97) + 
  facet_wrap(~ label, scales = "free_x")

#intercept:
posterior_samples(size_mod_ex_gaus_wprior) %>% 
  select(b_Intercept, prior_Intercept) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()

#slope:
posterior_samples(size_mod_ex_gaus_wprior) %>% 
  select(b_treatment_bNo_rats, prior_b) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()


#beta intercept:
posterior_samples(size_mod_ex_gaus_wprior) %>% 
  select(b_beta_Intercept, prior_Intercept_beta) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()

#beta slope:
posterior_samples(size_mod_ex_gaus_wprior) %>% 
  select(b_beta_treatment_bNo_rats, prior_b_beta) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()


#Compile posterior distributions:
size_post <- posterior_samples(size_mod_ex_gaus_wprior)
median_hdi(size_post$b_treatment_bNo_rats, .width = .95) #median estimate = 2.33, ymin = 0.13, ymax = 4.88
median_hdi(size_post$b_beta_treatment_bNo_rats, .width = .95) #median estimate = 0.46, ymin = 0.11, ymax = 0.83

#test hypothesis that birdy effect is > 0
hypothesis(size_mod_ex_gaus_wprior, c("treatment_bNo_rats > 0",  ##evidence ratio - 96.56, posterior prob = 0.99
                                    "beta_treatment_bNo_rats > 0"))  ##evidence ratio - 257.06, posterior prob = 1.0
##so, definitely an effect of birds on both the mean and skew of size distribution


###percent difference
2.42/((2.42+14.31+14.31)/2) ##15.59%


```


##Posterior plots for size
```{r}
##just plot mean for paper: 
size_post_plot<-
size_mod_ex_gaus_wprior %>%
  spread_draws(b_treatment_bNo_rats) %>%
 # mutate(exp_b=exp(b_treatment_bNo_rats))%>%
  ggplot(aes(y = 0, x = b_treatment_bNo_rats, fill = stat(x < 0))) +
  stat_halfeyeh(point_interval=median_hdi, .width=.95, fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#005AB5", "#DC3220"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("Length")+
  ylab("") +
  scale_y_continuous(NULL, breaks = NULL) +
#  scale_x_continuous(limits=c(-2.5, 2.5), breaks=seq(-2, 2,1))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.title.y = element_text(size=16, face="bold"))
size_post_plot


```


##Size histogram plot
```{r}
##get mean size per treatment to plot: 
groupmean<-
  cso_only_2018%>%
  group_by(Treatment) %>%
  summarize(mean_size = mean(Length))

##histogram: 
size_hist<-
ggplot(cso_only_2018, aes(x=Length, fill = Treatment)) + 
  geom_histogram(aes(y= ..density..), position="identity", binwidth = 2.5) + 
  geom_vline(data=groupmean, aes(xintercept=mean_size, color =Treatment, alpha = 0.9), linetype = "dashed") +
    scale_fill_manual(values = alpha(c("#005AB5", "#DC3220"), 0.6))+
    scale_colour_manual(values = c("#005AB5", "#DC3220"))+
   scale_y_continuous(expand = c(0, 0), limits = c(0, 0.16), breaks=seq(0,0.15,0.05))+ 
   scale_x_continuous( breaks=seq(5,35,5))+ 
  xlab("Length (cm)")+
  ylab("Density")+
   theme_bw() + 
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.text.x = element_text(size=16))

size_hist

```


####combine plots - density, biomass, size:
```{r}
####newest plots:
aligned_raw_plots_pop<-plot_grid(dens_boxplot_no0, bio_boxplot_no0, size_hist, ncol = 1, align = "hv")
aligned_raw_plots_pop

aligned_post_pop<-plot_grid(dens_post_plot, bio_post_plot, size_post_plot, ncol = 1, align = "hv")
aligned_post_pop


comb_plot_pop <-
  ggdraw() + 
  draw_plot(aligned_raw_plots_pop, x = 0, y = 0, width = 0.53, height = 1) + # draw_plot(aligned_raw_plots, x = 0, y = 0, width = 0.55, height = 1)
  draw_plot(aligned_post_pop,  x = 0.53, y = 0, width = 0.47, height = 1) #  draw_plot(post_plots,  x = 0.55, y = 0, width = 0.45, height = 1) 
comb_plot_pop

ggsave(filename = "fig3_dens_bio_size_plot_comb_3b.pdf", 
       plot = comb_plot_pop,
       width = 20, 
       height = 20,
       units = "cm",
       dpi = 300,
       family = "sans",
       useDingbats=FALSE)




####alternative:
dens_plot <-
  ggdraw() + 
  draw_plot(dens_boxplot_no0, x = 0, y = 0, width = 0.55, height = 1) +
  draw_plot(dens_post_plot,  x = 0.55, y = 0, width = 0.45, height = 1) 
dens_plot

bio_plot <-
  ggdraw() + 
  draw_plot(bio_boxplot_no0, x = 0, y = 0, width = 0.55, height = 1) +
  draw_plot(bio_post_plot,  x = 0.55, y = 0, width = 0.45, height = 1) 
bio_plot

size_plot <-
  ggdraw() + 
  draw_plot(size_hist, x = 0, y = 0, width = 0.55, height = 1) +
  draw_plot(size_post_plot,  x = 0.55, y = 0, width = 0.45, height = 1) 
size_plot


aligned_survey_plot<-plot_grid(dens_plot, bio_plot, size_plot, 
                    ncol = 1, align = c("v", "h"))
aligned_survey_plot



ggsave(filename = "dens_bio_size_plot_comb_3b.pdf", 
       plot = aligned_survey_plot,
       width = 20, 
       height = 20,
       units = "cm",
       dpi = 300,
       family = "sans",
       useDingbats=FALSE)


###older plots:
##need to align boxplots, because different widths (because different decimal places in y-axis)
dens_comb_plot <-
  ggdraw() + 
  draw_plot(dens_boxplot_no0, x = 0, y = 0, width = 0.5, height = 1) +
  draw_plot(dens_post_plot,  x = 0.5, y = 0, width = 0.5, height = 1) 
dens_comb_plot

bio_comb_plot <-
  ggdraw() + 
  draw_plot(bio_boxplot_no0, x = 0, y = 0, width = 0.5, height = 1) +
  draw_plot(bio_post_plot,  x = 0.5, y = 0, width = 0.5, height = 1) 
bio_comb_plot

size_comb_plot <-
  ggdraw() + 
  draw_plot(size_hist, x = 0, y = 0, width = 0.5, height = 1) +
  draw_plot(size_post_plot,  x = 0.5, y = 0, width = 0.5, height = 1) 
size_comb_plot


aligned_survey_plot2<-plot_grid(dens_comb_plot, bio_comb_plot, size_comb_plot,
                    ncol = 1, align = c("v", "h"))
aligned_survey_plot2


ggsave(filename = "dens_bio_size_plot_comb_june2.pdf", 
       plot = aligned_survey_plot2,
       width = 25, 
       height = 25,
       units = "cm",
       dpi = 300,
       family = "sans",
       useDingbats=FALSE)

#####

aligned_survey_plot<-plot_grid(dens_boxplot_no0, dens_post_plot, bio_boxplot_no0, bio_post_plot, size_hist, 
                    size_post_plot, 
                    ncol = 2, align = c("v", "h"))
aligned_survey_plot


ggsave(filename = "dens_bio_size_plot_comb.pdf", 
       plot = aligned_survey_plot,
       width = 17, 
       height = 17,
       units = "cm",
       dpi = 300,
       family = "sans",
       useDingbats=FALSE)


###set scales for posterior plots to be the same: 
bio_post_plot2<-
biomass_mod %>%
  spread_draws(b_treatment_bNo_rats) %>%
 # mutate(exp_b=exp(b_treatment_bNo_rats))%>%
  ggplot(aes(y = 0, x = b_treatment_bNo_rats, fill = stat(x < 0))) +
  stat_halfeyeh(point_interval=median_hdi, .width=.95, fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#005AB5", "#DC3220"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("Biomass")+
  ylab("") +
  scale_y_continuous(NULL, breaks = NULL) +
  scale_x_continuous(limits=c(-2.5, 8.5), breaks=seq(-2, 8,2))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.title.y = element_text(size=16, face="bold"))
bio_post_plot2



dens_post_plot2<-
density_mod %>%
  spread_draws(b_treatment_bNo_rats) %>%
 # mutate(exp_b=exp(b_treatment_bNo_rats))%>%
  ggplot(aes(y = 0, x = b_treatment_bNo_rats, fill = stat(x < 0))) +
  stat_halfeyeh(point_interval=median_hdi, .width=.95, fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#005AB5", "#DC3220"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("Density")+
  ylab("") +
  scale_y_continuous(NULL, breaks = NULL) +
  scale_x_continuous(limits=c(-2.5, 8.5), breaks=seq(-2, 8,2))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.title.y = element_text(size=16, face="bold"))
dens_post_plot2


size_post_plot2<-
size_mod_ex_gaus_wprior %>%
  spread_draws(b_treatment_bNo_rats) %>%
 # mutate(exp_b=exp(b_treatment_bNo_rats))%>%
  ggplot(aes(y = 0, x = b_treatment_bNo_rats, fill = stat(x < 0))) +
  stat_halfeyeh(point_interval=median_hdi, .width=.95, fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#005AB5", "#DC3220"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("Length")+
  ylab("") +
  scale_y_continuous(NULL, breaks = NULL) +
  scale_x_continuous(limits=c(-2.5, 8.5), breaks=seq(-2, 8,2))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.title.y = element_text(size=16, face="bold"))
size_post_plot2



aligned_survey_plot2<-plot_grid(dens_boxplot_no0, dens_post_plot2, bio_boxplot_no0, bio_post_plot2, size_hist, 
                    size_post_plot2, 
                    ncol = 2, align = c("v", "h"))
aligned_survey_plot2


ggsave(filename = "dens_bio_size_plot_comb2.pdf", 
       plot = aligned_survey_plot2,
       width = 17, 
       height = 17,
       units = "cm",
       dpi = 300,
       family = "sans",
       useDingbats=FALSE)

```


