---
title: "R Notebook: C. sordidus growth analyses"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

#Step 0: Load packages
```{r}
library(tidyverse)
library(brms)
library(tidybayes)
library(modelr) #for data_grid function
library(bayesplot)
library(gridExtra) #for plots
library(RColorBrewer) #for plots
library(cowplot) #for plots
library(scales) #for plots
```


#Step 1: Load data
```{r}
load("cso_data.Rdata")

head(cso_dat_lfm)
str(cso_dat_lfm)

#create indicator variable
cso_dat_lfm$tin<-ifelse(cso_dat_lfm$treatment=="ratty", 0, 1)
```


#Final models (earlier versions built up models slowly, compared different priors, etc. - all came to same conclusions)
#VBGF models
```{r}

#need to specify priors for nl models
#based on priors in Graham et al. 2018 (who used same formula)
vbgf_prior<- c(
  prior(uniform(15.2, 53.6), nlpar = "Linf", lb = 15.2, ub = 53.6), #constraind between minimum size and twice maximum
  prior(uniform(0,2), nlpar = "K", lb=0, ub = 2), #constrained because must be > 0, and k not > 2
  prior(uniform(0, 15.2), nlpar = "L0", lb = 0, ub = 15.2), ###L0 constrained bewettn 0 and minimum size observed
  prior(normal(0, 1), nlpar = "K1") ###weak, to allow either positive or negative (or 0) birdy effect
)

#run model
vbgf_mod <- 
  brm(
    bf(
      llength ~ log(Linf-(Linf-L0)*exp(-(K+K1*tin)*age_final)),
      Linf~1, K~1+(1|atoll), L0~1, K1~1,
      nl=TRUE),
    data = cso_dat_lfm, family = gaussian,
    prior = vbgf_prior,
      iter = 3000, warmup = 1000, chains = 4, cores = 4,
    control = list(adapt_delta = 0.9999, max_treedepth=15), 
    sample_prior=TRUE,
      file = "vbgf_mod"
  )
print(vbgf_mod) 
plot(vbgf_mod, ask = FALSE)
pp_check(vbgf_mod)
pairs(vbgf_mod)
#14 divergent transitions, but ess, and other diagnostics look good
prior_summary(vbgf_mod)

#compare posterior vs. prior distributions
#Linf:
posterior_samples(vbgf_mod) %>% 
  select(b_Linf_Intercept, prior_b_Linf) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()

#K:
posterior_samples(vbgf_mod) %>% 
  select(b_K_Intercept, prior_b_K) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()

#slope (rat):
posterior_samples(vbgf_mod) %>% 
  select(b_L0_Intercept, prior_b_L0) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()

#slope (rat):
posterior_samples(vbgf_mod) %>% 
  select(b_K1_Intercept, prior_b_K1) %>% 
  gather(Type, value) %>% 
    ggplot(aes(value, col=Type)) +
    geom_density()


#Compile posterior distributions:
vbgf_post <- posterior_samples(vbgf_mod)
median_hdi(vbgf_post$b_K1_Intercept, .width = .95) #median = 0.08, min = 0.21, max = 0.14


#test hypothesis that birdy effect is > 0
hypothesis(vbgf_mod, "K1_Intercept  > 0") ##evidence ratio = 469.59, posterior prob = 1

```

##Plots of posterior distribution
```{r}
###try some plots
###SUMMARY: (from page 100 of recoding_statistical rethinking PDF)
#highest posterior denisty estimates


vbgf_post_plot <-
vbgf_mod %>%
  spread_draws(b_K1_Intercept) %>%
  ggplot(aes(y = 0, x = b_K1_Intercept, fill = stat(x < 0))) +
  stat_halfeyeh(point_interval=median_hdi, .width=.95, fatten_point = 2, slab_alpha = 0.6) +
  scale_fill_manual(values = alpha(c("#005AB5", "#DC3220"),0.3))+
  geom_vline(xintercept = 0, linetype = "dashed") +
  theme_bw() + 
  xlab("K")+ 
  ylab("") +
  scale_y_continuous(NULL, breaks = NULL) +
  #scale_x_continuous(limits=c(-1.4, 0.25), breaks=seq(-1.4, 0.2, .2), labels = scales::number_format(accuracy = 0.1))+
  scale_x_continuous(limits=c(-0.05, 0.25), breaks=seq(0, 0.25,.1))+
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.text.x = element_text(size=16))
vbgf_post_plot

```


##Plots - now with raw data and estimated regression lines
```{r}

vbgf_plot<-
cso_dat_lfm %>%
  group_by(treatment) %>%
  add_fitted_draws(vbgf_mod, re_formula=NA) %>% #re_formula = NA to deal with random effects
  ggplot(aes(x = age_final, y = fork_length_cm, color = treatment, fill = treatment,  alpha = 0.6)) +
  geom_point(data = cso_dat_lfm, size = 3, aes(shape = ordered(treatment)))+
  stat_lineribbon(aes(y = exp(.value)), .width=0) +
   scale_fill_manual(values = c("#005AB5", "#DC3220")) + 
  scale_color_manual(values = c("#005AB5", "#DC3220")) +   
  scale_shape_manual(values = c(21,23)) + 
  theme_bw() + 
  xlab("Age (years)")+
  ylab("Length (cm)") +
  theme(panel.grid.major = element_blank(), # remove gridlines
        panel.grid.minor = element_blank(), #remove gridlines
        strip.background = element_blank(), 
        legend.position = "none",  
        rect = element_rect(fill = "transparent"),  
        plot.background = element_rect(fill = "transparent", color = NA),
        text=element_text(size=16,  family="sans"),
        axis.text.x = element_text(size=16))
vbgf_plot

```

##Combine plots
```{r}
vbgf_comb_plot <-
  ggdraw() + 
  draw_plot(vbgf_plot, x = 0, y = 0, width = 0.5, height = 1) +
  draw_plot(vbgf_post_plot,  x = 0.5, y = 0, width = 0.5, height = 1) 
vbgf_comb_plot

```


##Combine plots with gsi, whole weight plots (from other file)
```{r}

#from other file:
gsi_comb_plot
lw_comb_plot

#from this file:
vbgf_comb_plot <-
  ggdraw() + 
  draw_plot(vbgf_plot, x = 0, y = 0, width = 0.5, height = 1) +
  draw_plot(vbgf_post_plot,  x = 0.5, y = 0, width = 0.5, height = 1) 
vbgf_comb_plot


####combine these 3 into one:
ind_plots_comb<-plot_grid(vbgf_comb_plot, gsi_comb_plot, lw_comb_plot, ncol = 1, align = "v")
ind_plots_comb

ggsave(filename = "figure2_combined_aug25.pdf", 
       plot = ind_plots_comb,
       width = 20, 
       height = 20,
       units = "cm",
       dpi = 300,
       family = "sans",
       useDingbats=FALSE)

```
